/* Dual-mode JS: Simple + Pro */
const $$=s=>document.querySelector(s), $$$=s=>document.querySelectorAll(s);
const state={mode:'pro',ingredientsList:[],versionData:null,registration:null};
async function fetchJSON(u){const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw new Error(u+': '+r.status);return r.json();}
function setMode(m){state.mode=m;localStorage.setItem('pc_mode',m);renderMode();}
function renderMode(){$$('#simpleSection').hidden=state.mode!=='simple';$$('#proSection').hidden=state.mode!=='pro';$$$('.tab-btn').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));}
async function loadData(){try{const [ings,ver]=await Promise.all([fetchJSON('data/ingredients.json'),fetchJSON('version.json')]);state.ingredientsList=ings||[];state.versionData=ver?.data||null;const dl=$$('#ingredientList');dl.innerHTML='';state.ingredientsList.forEach(o=>{const op=document.createElement('option');op.value=o.name;dl.appendChild(op);});maybeShowUpdateBannerOnVersion();$$('#dataStatus')&&($$('#dataStatus').textContent=`Data loaded (version: ${state.versionData||'n/a'})`);}catch(e){console.error(e);$$('#dataStatus')&&($$('#dataStatus').textContent='Failed to load data.');}}
function maybeShowUpdateBannerOnVersion(){const c=state.versionData||null,s=localStorage.getItem('pc_data_version');if(s&&c&&s!==c)showUpdateBanner();if(c)localStorage.setItem('pc_data_version',c);}
function showUpdateBanner(){$$('#updateBanner').hidden=false;}
function setupUpdateRefresh(){$$('#refreshBtn').addEventListener('click',async()=>{if(state.registration?.waiting){state.registration.waiting.postMessage({type:'SKIP_WAITING'});}else{await Promise.all([fetch('version.json',{cache:'reload'}),fetch('data/ingredients.json',{cache:'reload'})]);window.location.reload();}});}
function setupTheme(){const sv=localStorage.getItem('pc_theme');if(sv)document.documentElement.setAttribute('data-theme',sv);syncThemeMeta();$$('#themeToggle').addEventListener('click',()=>{const c=document.documentElement.getAttribute('data-theme')||'light';const n=c==='light'?'dark':'light';document.documentElement.setAttribute('data-theme',n);localStorage.setItem('pc_theme',n);syncThemeMeta();});}
function syncThemeMeta(){const t=document.documentElement.getAttribute('data-theme')||'light';document.getElementById('theme-color-meta').setAttribute('content',t==='dark'?'#0e0f13':'#ffffff');}
function registerSW(){if('serviceWorker'in navigator){window.addEventListener('load',async()=>{try{const reg=await navigator.serviceWorker.register('./sw.js');state.registration=reg;function showIfWaiting(){if(reg.waiting)showUpdateBanner();}reg.addEventListener('updatefound',()=>{const nw=reg.installing;if(nw)nw.addEventListener('statechange',()=>{if(nw.state==='installed'&&navigator.serviceWorker.controller)showUpdateBanner();});});showIfWaiting();navigator.serviceWorker.addEventListener('controllerchange',()=>window.location.reload());}catch(e){console.warn('SW registration failed',e);}});}}
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;const b=$$('#installBtn');b.hidden=false;b.onclick=async()=>{b.hidden=true;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;};});
/* SIMPLE */
function s_addRow(d={name:'',pct:0}){const tb=$$('#tableBody');const tr=document.createElement('tr');const idx=document.createElement('td');idx.className='row-index';tr.appendChild(idx);const ntd=document.createElement('td');const ni=document.createElement('input');ni.type='text';ni.setAttribute('list','ingredientList');ni.value=d.name||'';ni.placeholder='Ingredient name';ni.addEventListener('input',s_update);ntd.appendChild(ni);tr.appendChild(ntd);const ptd=document.createElement('td');const pi=document.createElement('input');pi.type='number';pi.min='0';pi.max='100';pi.step='0.01';pi.value=d.pct??0;pi.addEventListener('input',s_update);ptd.appendChild(pi);tr.appendChild(ptd);const f=document.createElement('td');f.className='finished';f.textContent='0';tr.appendChild(f);['4','5A','5B','9'].forEach(c=>{const td=document.createElement('td');td.className='ifra ifra-'+c;td.innerHTML='<span class=\"status\">—</span>';tr.appendChild(td);});const a=document.createElement('td');const rm=document.createElement('button');rm.textContent='Remove';rm.className='danger';rm.onclick=()=>{tr.remove();s_update();};a.appendChild(rm);tr.appendChild(a);tb.appendChild(tr);s_renumber();s_update();}
function s_renumber(){$$$('#tableBody .row-index').forEach((td,i)=>td.textContent=i+1);}
function s_rows(){return Array.from($$$('#tableBody tr')).map(tr=>{const n=tr.querySelector('input[list]')?.value?.trim()||'';const pct=parseFloat(tr.querySelector('input[type=number]')?.value||'0');return{tr,name:n,pct:isNaN(pct)?0:pct};});}
function s_fin(p,d){return(p*d)/100;}
function s_badge(v,l){if(l==null||isNaN(l))return`<span class="status ok">n/a</span>`;if(v<=l){const r=l>0?(v/l):0;if(r>0.8)return`<span class="status warn">${v.toFixed(3)} ≤ ${l}%</span>`;return`<span class="status ok">${v.toFixed(3)} ≤ ${l}%</span>`;}return`<span class="status fail">${v.toFixed(3)} > ${l}%</span>`;}
function s_update(){const d=parseFloat($$('#dosage').value||'0');const rows=s_rows();let tc=0,tf=0;rows.forEach(({tr,name,pct})=>{tc+=pct;const fin=s_fin(pct,d);tf+=fin;tr.querySelector('.finished').textContent=fin.toFixed(3);const lim=(state.ingredientsList.find(i=>i.name===name)?.ifraLimits)||{};['4','5A','5B','9'].forEach(c=>{const L=parseFloat(lim?.[c]);tr.querySelector('.ifra-'+c).innerHTML=s_badge(fin,L);});});$$('#totalConcentrate').textContent=tc.toFixed(3);$$('#totalFinished').textContent=tf.toFixed(3);}
function s_bind(){$$('#addRow').onclick=()=>s_addRow();$$('#saveRecipe').onclick=s_save;$$('#loadRecipe').onclick=s_loadSel;$$('#deleteRecipe').onclick=s_delSel;$$('#exportCsv').onclick=s_csv;$$('#printBtn').onclick=()=>window.print();$$('#clearAll').onclick=()=>{if(!confirm('Clear all rows?'))return;$$('#tableBody').innerHTML='';s_addRow();s_update();};$$('#dosage').addEventListener('input',s_update);}
function s_save(){const n=$$('#recipeName').value.trim();if(!n){alert('Enter a recipe name');return;}const d=parseFloat($$('#dosage').value||'0');const rows=s_rows().map(r=>({name:r.name,pct:r.pct}));const all=JSON.parse(localStorage.getItem('pc_recipes_v1')||'{}');all[n]={dosage:d,rows};localStorage.setItem('pc_recipes_v1',JSON.stringify(all));s_pop(n);}
function s_pop(sel=''){const s=$$('#savedRecipes');const all=JSON.parse(localStorage.getItem('pc_recipes_v1')||'{}');s.innerHTML='';Object.keys(all).sort().forEach(k=>{const o=document.createElement('option');o.value=k;o.textContent=k;if(k===sel)o.selected=true;s.appendChild(o);});}
function s_loadSel(){const n=$$('#savedRecipes').value;const all=JSON.parse(localStorage.getItem('pc_recipes_v1')||'{}');const rec=all[n];if(!rec){alert('Not found');return;}$$('#tableBody').innerHTML='';$$('#dosage').value=rec.dosage;(rec.rows||[]).forEach(r=>s_addRow(r));s_update();}
function s_delSel(){const n=$$('#savedRecipes').value;const all=JSON.parse(localStorage.getItem('pc_recipes_v1')||'{}');if(!n||!all[n])return;if(!confirm(`Delete recipe "${n}"?`))return;delete all[n];localStorage.setItem('pc_recipes_v1',JSON.stringify(all));s_pop();}
function s_csv(){const rows=s_rows();const d=parseFloat($$('#dosage').value||'0');const heads=['#','Ingredient','% in concentrate','Dosage %','Finished %','IFRA 4','IFRA 5A','IFRA 5B','IFRA 9'];const lines=[heads.join(',')];rows.forEach((r,i)=>{const fin=s_fin(r.pct,d);const lim=(state.ingredientsList.find(x=>x.name===r.name)?.ifraLimits)||{};const cats=['4','5A','5B','9'];const sts=cats.map(c=>{const L=parseFloat(lim?.[c]);if(L==null||isNaN(L))return'n/a';return fin<=L?'OK':'FAIL';});lines.push([i+1,`"${(r.name||'').replace(/"/g,'""')}"`,r.pct,d,fin.toFixed(4),...sts].join(','));});const blob=new Blob([lines.join('\n')],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='perfume-recipe-simple.csv';a.click();URL.revokeObjectURL(url);}
/* PRO */
function p_newRow(d={}){const tr=document.createElement('tr');tr.innerHTML=`
<td><input type="text" class="p-name" list="ingredientList" placeholder="Type or select..." autocomplete="off"></td>
<td><input type="number" class="p-vol" step="0.01" value="${d.vol??0}"></td>
<td><input type="number" class="p-den" step="0.01" value="${d.den??0.85}"></td>
<td><input type="number" class="p-wt" step="0.01" value="${d.wt??0}"></td>
<td><input type="number" class="p-price" step="0.01" value="${d.price??0}"></td>
<td class="p-cost">0.00</td>
<td class="p-pct">0.00 %</td>
<td><select class="p-note"><option value="N/A">N/A</option><option>Top</option><option>Middle</option><option>Base</option></select></td>
<td><input type="text" class="p-supplier"></td>
<td><input type="text" class="p-cas"></td>
<td><textarea class="p-notes"></textarea></td>
<td class="p-del">❌</td>`;$$('#proBody').appendChild(tr);return tr;}
function p_rows(){return Array.from($$$('#proBody tr'));}
function p_calc(){const rows=p_rows();let tw=0,tv=0,tc=0;const noteW={Top:0,Middle:0,Base:0,'N/A':0};rows.forEach(tr=>{tw+=parseFloat(tr.querySelector('.p-wt').value)||0;});rows.forEach(tr=>{const v=parseFloat(tr.querySelector('.p-vol').value)||0;const d=parseFloat(tr.querySelector('.p-den').value)||0;const w=parseFloat(tr.querySelector('.p-wt').value)||0;const pr=parseFloat(tr.querySelector('.p-price').value)||0;const cost=(w/10)*pr;tr.querySelector('.p-cost').textContent=cost.toFixed(2);const pct=tw>0?(w/tw*100):0;tr.querySelector('.p-pct').textContent=pct.toFixed(2)+' %';tv+=v;tc+=cost;const note=tr.querySelector('.p-note').value;if(noteW[note]!=null)noteW[note]+=w;});$$('#proTotalVol').textContent=tv.toFixed(2);$$('#proTotalWt').textContent=tw.toFixed(2);$$('#proTotalCost').textContent=tc.toFixed(2);$$('#proTotalPct').textContent='100.00 %';let txt=[];for(const k in noteW){const pct=tw>0?(noteW[k]/tw*100).toFixed(1):'0.0';txt.push(`${k}: ${pct}%`);}$$('#noteSummaryText').textContent=txt.join(' | ');p_ifra();}
function p_ifra(){const cat=$$('#ifraCategory').value;const rows=p_rows();const bad=[];rows.forEach(tr=>{const name=(tr.querySelector('.p-name').value||'').trim();const pct=parseFloat(tr.querySelector('.p-pct').textContent)||0;const entry=state.ingredientsList.find(i=>(i.name||'').toLowerCase()===name.toLowerCase());const lim=entry?.ifraLimits?.[cat];if(lim!=null&&!isNaN(lim)&&pct>parseFloat(lim)){bad.push({name,pct:pct.toFixed(2),limit:lim});}});const st=$$('#ifraStatusText'),wrap=$$('#ifraStatus');if(bad.length){wrap.style.borderColor='var(--danger)';st.innerHTML=`<strong>⚠ Non-compliant for Cat ${cat}</strong><ul>`+bad.map(o=>`<li><b>${o.name}</b> ${o.pct}% > limit ${o.limit}%</li>`).join('')+`</ul>`;}else{wrap.style.borderColor='var(--ok)';st.innerHTML=`<strong>✅ Compliant for Cat ${cat}</strong>`;}}
function p_onInput(e){const tr=e.target.closest('tr');if(!tr)return;if(e.target.classList.contains('p-name')){const sel=state.ingredientsList.find(i=>i.name===e.target.value);if(sel){tr.querySelector('.p-cas').value=sel.casNumber||'';tr.querySelector('.p-price').value=sel.pricePer10g||0;tr.querySelector('.p-notes').value=sel.notes||'';tr.querySelector('.p-den').value=sel.density||tr.querySelector('.p-den').value;}}if(e.target.classList.contains('p-vol')||e.target.classList.contains('p-den')){const v=parseFloat(tr.querySelector('.p-vol').value)||0;const d=parseFloat(tr.querySelector('.p-den').value)||0;tr.querySelector('.p-wt').value=(v*d).toFixed(3);}else if(e.target.classList.contains('p-wt')){const d=parseFloat(tr.querySelector('.p-den').value)||0;if(d>0){tr.querySelector('.p-vol').value=(parseFloat(tr.querySelector('.p-wt').value)/d).toFixed(3);}}p_calc();}
function p_bind(){$$('#proAdd').onclick=()=>{p_newRow();p_calc();};$$('#proBody').addEventListener('input',p_onInput);$$('#proBody').addEventListener('change',p_calc);$$('#proBody').addEventListener('click',e=>{if(e.target.classList.contains('p-del')){e.target.closest('tr').remove();p_calc();}});$$('#ifraCategory').onchange=p_ifra;$$('#proPrint').onclick=()=>window.print();$$('#proSave').onclick=p_save;$$('#proLoad').onclick=p_loadSel;$$('#proDelete').onclick=p_delSel;$$('#proNew').onclick=()=>{$$('#proBody').innerHTML='';p_newRow();p_calc();};const hc=$$('#helperCost'),hw=$$('#helperWeight'),out=$$('#helperResult');function upd(){const c=parseFloat(hc.value)||0;const w=parseFloat(hw.value)||0;out.textContent=w>0?`€${(c/w*10).toFixed(2)} per 10g`:'€0.00 per 10g';}hc.oninput=upd;hw.oninput=upd;$$('#proExport').onclick=p_csv;}
function p_collect(){return Array.from($$$('#proBody tr')).map(tr=>({name:(tr.querySelector('.p-name').value||'').trim(),vol:parseFloat(tr.querySelector('.p-vol').value)||0,den:parseFloat(tr.querySelector('.p-den').value)||0,wt:parseFloat(tr.querySelector('.p-wt').value)||0,price:parseFloat(tr.querySelector('.p-price').value)||0,note:tr.querySelector('.p-note').value||'N/A',supplier:tr.querySelector('.p-supplier').value||'',cas:tr.querySelector('.p-cas').value||'',notes:tr.querySelector('.p-notes').value||''}));}
function p_save(){const n=prompt('Recipe name?');if(!n)return;const payload={cat:$$('#ifraCategory').value,targetVol:parseFloat($$('#targetVolume').value)||0,rows:p_collect()};const all=JSON.parse(localStorage.getItem('pc_pro_recipes_v1')||'{}');all[n]=payload;localStorage.setItem('pc_pro_recipes_v1',JSON.stringify(all));p_pop(n);}
function p_pop(sel=''){const s=$$('#proSaved');const all=JSON.parse(localStorage.getItem('pc_pro_recipes_v1')||'{}');s.innerHTML='';Object.keys(all).sort().forEach(k=>{const o=document.createElement('option');o.value=k;o.textContent=k;if(k===sel)o.selected=true;s.appendChild(o);});}
function p_loadSel(){const n=$$('#proSaved').value;const all=JSON.parse(localStorage.getItem('pc_pro_recipes_v1')||'{}');const rec=all[n];if(!rec){alert('Not found');return;}$$('#ifraCategory').value=rec.cat||'4';$$('#targetVolume').value=rec.targetVol||0;$$('#proBody').innerHTML='';(rec.rows||[]).forEach(r=>p_newRow(r));p_calc();}
function p_delSel(){const n=$$('#proSaved').value;const all=JSON.parse(localStorage.getItem('pc_pro_recipes_v1')||'{}');if(!n||!all[n])return;if(!confirm(`Delete recipe "${n}"?`))return;delete all[n];localStorage.setItem('pc_pro_recipes_v1',JSON.stringify(all));p_pop();}
function p_csv(){const rows=p_collect();const heads=['Ingredient','Volume (ml)','Density (g/ml)','Weight (g)','Price/10g (€)','Cost (€)','Formula % (by wt)','Note','Supplier','CAS','Notes'];const lines=[heads.join(',')];const tw=rows.reduce((a,b)=>a+(b.wt||0),0);rows.forEach(r=>{const cost=(r.wt/10)*(r.price||0);const pct=tw>0?(r.wt/tw*100):0;lines.push([`"${(r.name||'').replace(/"/g,'""')}"`,r.vol,r.den,r.wt,(r.price||0).toFixed(2),cost.toFixed(2),pct.toFixed(2),r.note,r.supplier,r.cas,`"${(r.notes||'').replace(/"/g,'""')}"`].join(','));});const blob=new Blob([lines.join('\n')],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='perfume-recipe-pro.csv';a.click();URL.revokeObjectURL(url);}
/* INIT */
function bindGlobal(){$$('#modeSimple').onclick=()=>setMode('simple');$$('#modePro').onclick=()=>setMode('pro');}
function init(){const m=localStorage.getItem('pc_mode');setMode(m||'pro');setupTheme();bindGlobal();setupUpdateRefresh();s_bind();s_addRow();p_bind();p_newRow();loadData();registerSW();}
document.addEventListener('DOMContentLoaded',init);
